global:
  scrape_interval: 15s
  evaluation_interval: 15s

# rule_files:
#   - '/etc/prometheus/alerts/*.yml'


scrape_configs:
  - job_name: node
    static_configs:
    - targets: ['192.168.1.131:9100','79.137.194.165:9100','178.154.245.52:9100','192.168.1.2:9100','79.137.205.253:9100','192.168.1.157:9100']

  - job_name: 'cadvisor'
    scrape_interval: 15s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          group: 'cadvisor'
          
  - job_name: 'traefik'
    static_configs:
    - targets: ['traefik:8084']

  # - job_name: truenas
  #   scrape_interval: 15s
  #   metrics_path: /metrics
  #   static_configs:
  #   - targets: ['graphite-exporter:9108']
